### ISSUE TITLE
Hey, would you be able to make it like a wizard?

### ISSUE THREAD

**Issue by gaining** [pp19dd/picker#3]
Basically the ability to pick from multiple lists, one after the other and navigating forward and backwards?

**Comment by pp19dd** [comment]
Sorry to get back so late, but no, not in the current form.  To make this more flexible for that purpose, I'd need to add some hooks for the class to be dynamically extended perhaps (for example so that you can preload checkmarks, or make it a radio box of sorts), or make it multi-window.  While this project is seemingly neglected, I've done some updates today (about time) and while they did nothing for you, I will take your request into consideration for upcoming changes.  Kind regards.

**Comment by gaining** [comment]
I have done it. You can see here: https://github.com/gaining/resetter-cli/blob/master/resetter-cli/picker.py
